# Generated by Django 5.2.7 on 2026-02-13 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_user_id_cart_user_and_more'),
        ('userlogin', '0003_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.user'),
        ),
    ]
