# Generated by Django 5.2.7 on 2026-02-13 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
