# Generated by Django 5.2.7 on 2026-02-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
