# Generated by Django 5.2.7 on 2026-02-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
