# Generated by Django 5.2.7 on 2026-02-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
